<a href="https://colab.research.google.com/github/onlookertozip/bigStudy/blob/master/%EC%88%98%ED%95%99%ED%95%A8%EC%88%98_%EB%B3%B4%EC%B6%A9%EC%9E%90%EB%A3%8C_%EA%B8%B0%EC%88%A0%ED%86%B5%EA%B3%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 파이썬을 이용한 기술통계: 1변량 데이터

## 


### scipy

In [ ]:
import numpy as np
import scipy as sp

# 소수점 이하 자릿수 3
%precision 3

'%.3f'

### 1변량 데이터 관리

In [ ]:
fish_data = np.array([2,3,3,4,4,4,4,5,5,6])
fish_data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

### 합계와 샘플사이즈

In [ ]:
# 합계
sp.sum(fish_data)

40

In [ ]:
# 샘플사이즈
len(fish_data)

10

### 평균값

In [ ]:
N = len(fish_data)
sum_value = sp.sum(fish_data)
mu = sum_value / N
mu

4.000

In [ ]:
sp.mean(fish_data)

4.000

### 표본분산

In [ ]:
sigma_2_sample = sp.sum((fish_data - mu) ** 2) / N
sigma_2_sample

1.200

In [ ]:
fish_data

array([2, 3, 3, 4, 4, 4, 4, 5, 5, 6])

In [ ]:
fish_data - mu

array([-2., -1., -1.,  0.,  0.,  0.,  0.,  1.,  1.,  2.])

In [ ]:
(fish_data - mu) ** 2

array([ 4.,  1.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  4.])

In [ ]:
sp.sum((fish_data - mu) ** 2)

12.000

In [ ]:
sp.var(fish_data, ddof = 0)

1.200

ddof : int, 선택 사항
델타 자유도를 의미합니다. 계산에 사용되는 제수는 N-ddof이며, 여기서 N은 요소 수를 나타냅니다. 기본적으로 ddof는 0입니다.모분산은 ddof = 0, 표본분산은 ddof = 1
넘파이는 ddof = 0이 디폴트, 판다스는 ddof = 1 이 디폴트

### 불편분산

In [ ]:
sigma_2 = sp.sum((fish_data - mu) ** 2) / (N - 1)
sigma_2

1.333

In [ ]:
sp.var(fish_data, ddof = 1)

1.333

### 표준편차

In [ ]:
sigma = sp.sqrt(sigma_2)
sigma

1.155

In [ ]:
sp.std(fish_data, ddof = 1)

1.155

### 표준화

In [ ]:
fish_data - mu

array([-2., -1., -1.,  0.,  0.,  0.,  0.,  1.,  1.,  2.])

In [ ]:
sp.mean(fish_data - mu)

0.000

In [ ]:
fish_data / sigma

array([ 1.732,  2.598,  2.598,  3.464,  3.464,  3.464,  3.464,  4.33 ,
        4.33 ,  5.196])

In [ ]:
sp.std(fish_data / sigma, ddof = 1)

1.000

In [ ]:
standard = (fish_data - mu) / sigma
standard

array([-1.732, -0.866, -0.866,  0.   ,  0.   ,  0.   ,  0.   ,  0.866,
        0.866,  1.732])

In [ ]:
sp.mean(standard)

0.000

In [ ]:
sp.std(standard, ddof = 1)

1.000

### 기타 통계량

In [ ]:

sp.amax(fish_data)

6

In [ ]:

sp.amin(fish_data)

2

In [ ]:

sp.median(fish_data)

4.000

In [ ]:
fish_data_2 = np.array([2,3,3,4,4,4,4,5,5,100])

In [ ]:
sp.mean(fish_data_2)

13.400

In [ ]:
sp.median(fish_data_2)

4.000

### scipy.stats와 사분위수

In [ ]:
from scipy import stats

In [ ]:
fish_data_3 = np.array([1,2,3,4,5,6,7,8,9])
stats.scoreatpercentile(fish_data_3, 25)

3.000

In [ ]:
stats.scoreatpercentile(fish_data_3, 75)

7.000

#기술통계 예-와인 품질 데이터 셋

In [9]:
#!/usr/bin/env python3
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.api as sm
import statsmodels.formula.api as smf
from statsmodels.formula.api import ols, glm


# Read the data set into a pandas DataFrame
wine = pd.read_csv('winequality-both.csv', sep=',', header=0)
wine.columns = wine.columns.str.replace(' ', '_')
print(wine.head())

# Display descriptive statistics for all variables
print(wine.describe())

# Identify unique values
print(sorted(wine.quality.unique()))

# Calculate value frequencies
print(wine.quality.value_counts())

# Display descriptive statistics for quality by wine type
print(wine.groupby('type')[['alcohol']].describe().unstack('type'))

# Calculate specific quantiles
print(wine.groupby('type')[['quality']].quantile([0.25, 0.75]).unstack('type'))


  type  fixed_acidity  volatile_acidity  ...  sulphates  alcohol  quality
0  red            7.4              0.70  ...       0.56      9.4        5
1  red            7.8              0.88  ...       0.68      9.8        5
2  red            7.8              0.76  ...       0.65      9.8        5
3  red           11.2              0.28  ...       0.58      9.8        6
4  red            7.4              0.70  ...       0.56      9.4        5

[5 rows x 13 columns]
       fixed_acidity  volatile_acidity  ...      alcohol      quality
count    6497.000000       6497.000000  ...  6497.000000  6497.000000
mean        7.215307          0.339666  ...    10.491801     5.818378
std         1.296434          0.164636  ...     1.192712     0.873255
min         3.800000          0.080000  ...     8.000000     3.000000
25%         6.400000          0.230000  ...     9.500000     5.000000
50%         7.000000          0.290000  ...    10.300000     6.000000
75%         7.700000          0.400000  ...

# 기술통계 예-고객 데이터 셋

In [7]:
#!/usr/bin/env python3
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.api as sm
import statsmodels.formula.api as smf

# Read the data set into a pandas DataFrame
churn = pd.read_csv('customer.csv', sep=',', header=0)

churn.columns = [heading.lower() for heading in \
churn.columns.str.replace(' ', '_').str.replace("\'", "").str.strip('?')]

churn['churn01'] = np.where(churn['churn'] == 'True.', 1., 0.)
print(churn.head())
print(churn.describe())


# Calculate descriptive statistics for grouped data
print(churn.groupby(['churn'])[['day_charge', 'eve_charge', 'night_charge', 'intl_charge', 'account_length', 'custserv_calls']].agg(['count', 'mean', 'std']))

# Specify different statistics for different variables
print(churn.groupby(['churn']).agg({'day_charge' : ['mean', 'std'], 
				'eve_charge' : ['mean', 'std'],
				'night_charge' : ['mean', 'std'],
				'intl_charge' : ['mean', 'std'],
				'account_length' : ['count', 'min', 'max'],
				'custserv_calls' : ['count', 'min', 'max']}))

  state  account_length  area_code  ... custserv_calls   churn churn01
0    KS             128        415  ...              1  False.     0.0
1    OH             107        415  ...              1  False.     0.0
2    NJ             137        415  ...              0  False.     0.0
3    OH              84        408  ...              2  False.     0.0
4    OK              75        415  ...              3  False.     0.0

[5 rows x 22 columns]
       account_length    area_code  ...  custserv_calls      churn01
count     3333.000000  3333.000000  ...     3333.000000  3333.000000
mean       101.064806   437.182418  ...        1.562856     0.144914
std         39.822106    42.371290  ...        1.315491     0.352067
min          1.000000   408.000000  ...        0.000000     0.000000
25%         74.000000   408.000000  ...        1.000000     0.000000
50%        101.000000   415.000000  ...        1.000000     0.000000
75%        127.000000   510.000000  ...        2.000000     0.000000